# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.
AllCops:
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'frontend/**/*'

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true