version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - checkout # check out source code to working directory

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - calendar-demo-bundle-v1-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - calendar-demo-bundle-v1-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: calendar-demo-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Restore npm cache
      - restore_cache:
          keys:
            - calendar-demo-npm-v1-{{ checksum "frontend/package-lock.json" }}
            - calendar-demo-npm-v1-

      - run:
          name: NPM Install
          command: |
            cd frontend
            npm install
            cd ..

      # Store npm cache
      - save_cache:
          key: calendar-demo-npm-v1-{{ checksum "frontend/package-lock.json" }}
          paths:
            - frontend/node_modules

      # Install ember-cli globally
      - run: sudo npm install -g ember-cli

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            echo "Testing backend"

            bundle exec rspec spec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \

            echo "Testing frontend"

            cd frontend
            ember test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Production to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git production

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: production
