default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: satchel_dev

test:
  <<: *default
  database: satchel_test

production:
  <<: *default
  database: satchel_prod
