default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: event_calendar_development

test:
  <<: *default
  database: event_calendar_test
