default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: smhw_event_calendar_dev

test:
  <<: *default
  database: smhw_event_calendar_test

production:
  <<: *default
  database: smhw_event_calendar_db
